import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { useEffect, useState } from "react";
const inter = Inter({ subsets: ["latin"] });

export default function Home({ blogs }) {
  const [q,setQ]=useState("")
  const [blog,setBlog]=useState([])
  console.log(blogs.blog);
  useEffect(()=>{
fetch(`http://localhost:3005/blog?query=${q}`).then((res)=>res.json())
.then(res=>setBlog(res.blog)).catch((err)=>console.log(err))
  },[])
  console.log(blog)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <input type="text" placeholder="...search" onChange={(e)=>setQ(e.target.value)}/>
        <div>
          {blog.length===0?blogs.blog.map((el) => {
            return <Link href={`/content/${el._id}`}>
              <div className="space-y-1 mt-5" key={el._id}>
                <h3 className="font-bold">{el.title}</h3>

                <p>{el.content}...</p>
                <img src={el.image} />
              </div>
            </Link>;
          }):blog.map((el) => {
            return <Link href={`/content/${el._id}`}>
              <div className="space-y-1 mt-5" key={el._id}>
                <h3 className="font-bold">{el.title}</h3>

                <p>{el.content}...</p>
                <img src={el.image} />
              </div>
            </Link>;
          })}
          
        </div>
      </main>
    </>
  );
}
export async function getServerSideProps(context) {
  let data = await fetch(`http://localhost:3005/blog`);
  let res = await data.json();
  return {
    props: { blogs: JSON.parse(JSON.stringify(res)) },
  };
}
